function initUhq(this)

set(this.Gui.InstrumentMenu,'String',{'Select the device',...
    'Oscilloscope 1 (Tektronix DPO 4034)',...
    'Spectrum Analyzer (Agilent MXA)',...
    'UHF Lock-in Amplifier (Zurich Instrument)',...
    'Network Analyzer (Agilent NA)',...
    'Auto Ringdown (Agilent NA)'});

this.save_dir='W:\Measurement Campaigns\';
set(this.Gui.SaveDir,'String',this.save_dir);

end