function initRt(this)

set(this.Gui.InstrumentMenu,'String',{'Select the device',...
    'RT Oscilloscope 1 (Tektronix DPO 4034)',...
    'UHF Lock-in Amplifier (Zurich Instrument)',...
    'RT Spectrum Analyzer (RSA)',...
    'Oscilloscope 2 (Agilent DSO7034A)',...
    'Network Analyzer (Agilent E5061B)'});
this.save_dir='M:\Measurement Campaigns\';
set(this.Gui.SaveDir,'String',this.save_dir);

end