function initUhq(this)
this.save_dir='W:\Measurement Campaigns\';

if this.enable_gui
    set(this.Gui.InstrumentMenu,'String',{'Select the device',...
        'Oscilloscope 1 (Tektronix DPO 4034)',...
        'Spectrum Analyzer (Agilent MXA)',...
        'UHF Lock-in Amplifier (Zurich Instrument)',...
        'Network Analyzer (Agilent NA)',...
        'Auto Ringdown (Agilent NA)'});
    set(this.Gui.SaveDir,'String',this.save_dir);
end

end