% Verify that the object satisfies basic requirements for a
% DAQ-compatible analysis routine

function validateAnalysisRoutine(~, Obj)
    assert(ismember('NewFit', events(Obj)), ['Analysis routine of ' ...
        'class ' class(Obj) ' must define NewFit event to be used ' ...
        'with DAQ.'])
    
    assert(isprop(Obj, 'Data'), ['Analysis routine of ' ...
        'class ' class(Obj) ' must define Data property to be used ' ...
        'with DAQ.'])
    
     assert(isprop(Obj, 'Fit'), ['Analysis routine of ' ...
        'class ' class(Obj) ' must define Fit property to be used ' ...
        'with DAQ.'])
end

