%Class for NewData events that are generated by MyDataSource and its
%subclasses, including MyInstrument

classdef MyNewAnalysisTraceEvent < event.EventData
    
    properties (Access = public)
        analysis_type   char
        Trace           MyTrace
        trace_name      char
    end
    
    methods (Access = public)
        function this = MyNewAnalysisTraceEvent(varargin)
            P = MyClassParser(this);
            processInputs(P, this, varargin{:});
        end
    end
end

