%Class for NewData events that are generated by MyDataSource and its
%subclasses, including MyInstrument

classdef MyNewAnalysisTraceEvent < event.EventData
    
    properties (Access = public)
        Trace   MyTrace
    end
    
    methods (Access = public)
        function this = MyNewAnalysisTraceEvent(varargin)
            P = MyClassParser(this);
            processInputs(P, this, varargin{:});
        end
    end
end

