function createMechTab(this,bg_color, button_h)
this.Gui.MechTab=uix.Panel('Parent', this.Gui.TabPanel,...
    'Padding', 0, 'BackgroundColor',bg_color);

createUnitDisp(this,bg_color,this.Gui.MechTab,'Mech');

this.Gui.QLabel=annotation(this.Gui.MechNameVBox,'textbox',[0.5,0.5,0.3,0.3],...
    'String','Quality Factor','Units','Normalized',...
    'HorizontalAlignment','Left','VerticalAlignment','middle',...
    'FontSize',10,'BackgroundColor',bg_color);
this.Gui.QValue=uicontrol('Parent',this.Gui.MechValueVBox,...
    'Style','edit','String',1,'HorizontalAlignment','Right',...
    'FontSize',10,'Tag','EditFreq','Enable','off');

this.Gui.FreqLabel=annotation(this.Gui.MechNameVBox,'textbox',[0.5,0.5,0.3,0.3],...
    'String','Frequency (MHz)','Units','Normalized',...
    'HorizontalAlignment','Left','VerticalAlignment','middle',...
    'FontSize',10,'BackgroundColor',bg_color);
this.Gui.FreqValue=uicontrol('Parent',this.Gui.MechValueVBox,...
    'Style','edit','String',1,'HorizontalAlignment','Right',...
    'FontSize',10,'Tag','EditFreq');

this.Gui.LwLabel=annotation(this.Gui.MechNameVBox,'textbox',[0.5,0.5,0.3,0.3],...
    'String','Linewidth (Hz)','Units','Normalized',...
    'HorizontalAlignment','Left','VerticalAlignment','middle',...
    'FontSize',10,'BackgroundColor',bg_color);
this.Gui.LwValue=uicontrol('Parent',this.Gui.MechValueVBox,...
    'Style','edit','String',1,'HorizontalAlignment','Right',...
    'FontSize',10,'Tag','EditFreq');


set(this.Gui.MechNameVBox,'Heights',button_h*ones(1,3));
set(this.Gui.MechValueVBox,'Heights',button_h*ones(1,3));
end