classdef MyGaussianFit < MyFit
    %Public methods
    methods (Access=public)
        %Constructor function
        function this=MyGaussianFit(varargin)
            this@MyFit(...
                'fit_name','Gaussian',...
                'fit_function','a*exp(-((x-c)/b)^2/2)+d',...
                'fit_tex', '$$ae^{-\frac{(x-c)^2}{2b^2}}+d$$',...
                'fit_params',{'a','b','c','d'},...
                'fit_param_names',{'Amplitude','Width','Center','Offset'},...
                varargin{:});
        end
    end
    methods (Access=protected)
        function [init_params,lim_lower,lim_upper]=calcInitParams(this)
            [init_params,lim_lower,lim_upper]=...
                initParamGaussian(this.Data.x,this.Data.y);
        end
    end
end